version: '3'
networks:
  sail:
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default_000.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - sail
    user:
      1000:1000
  mysql:
    image: mysql:8.0.29-oracle
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - sail
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_USER: root
      # PMA_PASSWORD: 123
      PMA_ARBITRARY: 1
    networks:
      - sail